### PR TITLE
Verifying Tictactoe

### PR DESCRIPTION
**Pull request by sumith1896**
@regb I have two-player implementation as of now. What checks do we verify here?
Verifying one player AI version would be more interesting. A good implementation in ScalaJS is here
https://github.com/1984weed/tic-tac-toe-ai running http://1984weed.github.io/tic-tac-toe-ai/ 
Cheers.

### CODE REVIEW

**Comment by sumith1896** [comment]
PS: Need an update to your master to remove the extra commits

**Comment by regb** [comment]
Hey, sorry for the delay.
I made a branch game/tictactoe on my repository, rebased on master and included your commits. I also did some refactorings to the code, in particular I replaced the content of the Node by a Player object, which is more type safe than a raw number. I adapted the rest of the code to this.

I also added a few requires and a class invariant that checks there is always a different of at most one entry between the two players. I think we can maybe try to verify that the play action will always play with the right player (not two X in a row)

**Comment by regb** [comment]
current commit is 35ad2141036aec4f608f218a650d1a68ca9ef35c

**Comment by sumith1896** [comment]
Interesting, thanks for the updates. For two player version this is as good as 2048 for now. You can commit this to master when you feel like. 
For the one player AI, more interesting contracts can be verified:
- [ ] AI plays in the right move
- [ ] AI never loses

**Comment by sumith1896** [comment]
Shall I close this PR? As you have the commits in the new branch

**Comment by regb** [comment]
sure

**Comment by sumith1896** [comment]
Thanks!

**Pull request closed without merging**
